### ISSUE TITLE
Would release the code in the simulated environment RLBench.

### ISSUE THREAD

**Issue by siaoliu** [davidyyd/roboprompt#1]
Thanks for this awesome work!
I noticed early work like KAT just opened the prompt demo in the jupyter style (confusing). :<
Does the author open the whole pipeline?
Looking forward to your reply and hope to gain more insight from this work.

**Comment by davidyyd** [comment]
Hi @feriorior,

Thanks for your interest in our work!

1. Sorry for the delay in code release. I am preoccupied with other things in the last few weeks. We will release full code to reproduce our results in RLBench earlier next week. 
2. Yes. We do realize KAT provides jupyter notebook that shows how to identify keypoints in image pair. We use it to evaluate results for KAT.

**Comment by MarSaKi** [comment]
> Hi @feriorior,
> 
> Thanks for your interest in our work!
> 
> 1. Sorry for the delay in code release. I am preoccupied with other things in the last few weeks. We will release full code to reproduce our results in RLBench earlier next week.
> 2. Yes. We do realize KAT provides jupyter notebook that shows how to identify keypoints in image pair. We use it to evaluate results for KAT.

Dear author,  
Thanks for your great work! May I kindly inquire about the release progress of the amazing work?
Thanks for your attention to this matter.

**Comment by hoh12131** [comment]
> Hi @feriorior,
> 
> Thanks for your interest in our work!
> 
> 1. Sorry for the delay in code release. I am preoccupied with other things in the last few weeks. We will release full code to reproduce our results in RLBench earlier next week.
> 2. Yes. We do realize KAT provides jupyter notebook that shows how to identify keypoints in image pair. We use it to evaluate results for KAT.


Hi Author,
I was wondering if you could share any updates on the release progress.
Thank you for your time and consideration.

**Comment by davidyyd** [comment]
Hi @hoh12131 and @MarSaKi,

Sorry for the delay. It's up now.
